language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
gemfile:
  - gemfiles/activemodel-4
  - gemfiles/activemodel-3-2
  - gemfiles/standalone
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/activemodel-4